### ISSUE TITLE
Issue checking django.core.mail.outbox when using --parallel

### ISSUE THREAD

**Issue by grantmcconnaughey** [ojii/django-better-test#2]
I am receiving an error in one of my tests when I use the --parallel option. My test checks `django.core.mail.outbox` to ensure that an email was sent. Here is the error:

```
Traceback (most recent call last):
  File "/Users/grant/Dev/django/project/project/apps/myapp/tests/test_utils.py", line 38, in test_send_screen_share_alert
    message = mail.outbox[0]
IndexError: list index out of range
```

In `SimpleTestCase`, the `_pre_setup()` method resets `django.core.mail.outbox` to an empty list. Here's the code:

```
def _pre_setup(self):
    """Performs any pre-test setup. This includes:

    * Creating a test client.
    * If the class has a 'urls' attribute, replace ROOT_URLCONF with it.
    * Clearing the mail test outbox.
    """
    self.client = self.client_class()
    self._urlconf_setup()
    mail.outbox = []
```

I think the outbox gets set back to an empty list between the time that my test starts and when I check `outbox`.

If it helps, here is the test:

```
def test_send_screen_share_alert(self):
    user = UserFactory()
    phone_number = '417-555-1234'
    screen_share_link = ScreenShareLinkFactory()

    send_screen_share_alert(user=user, phone_number=phone_number,
                            screen_share_link=screen_share_link)

    message = mail.outbox[0]
    self.assertEqual(len(mail.outbox), 1)
    self.assertEqual(message.subject, 'Screen Share Alert')
    self.assertIn(phone_number, message.body)
    self.assertIn(screen_share_link.viewer_url, message.alternatives[0][0])
    self.assertIn(user.get_full_name(), message.body)
```

At the top of my file I am importing `django.core.mail`. I am using Django 1.8.3, Python 2.7.9, Mac OS X 10.10.5.

**Comment by ojii** [comment]
Could you try running this failing test alone either without better-test or using the `--vanilla` flag to see if the issue is that the test method itself is flawed (relies on other test methods being run in the same process) or if this is indeed an issue in better-test? The `--parallel` option sometimes shows flaws in test suites where methods leak state (and other methods then rely on that leak).

**Comment by grantmcconnaughey** [comment]
I ran the test again with the --vanilla option and the error did not occur.

**Comment by ojii** [comment]
Just to double check, you only ran that single test (not the whole suite) with --vanilla?

**Comment by grantmcconnaughey** [comment]
I ran the whole test suite with vanilla and it worked. I ran the whole test suite with parallel and the issue occurred.

**Comment by ojii** [comment]
The interesting bit is whether running that failing test alone (eg `python manage.py test yourapp.tests.YourTestCass.test_my_test`) makes it fail under vanilla.

**Comment by grantmcconnaughey** [comment]
Here are my test results. I ran it at the module level (with 3 tests) and the test level (just the one test that is failing). I ran it with the `--vanilla` option and the `--parallel` option. Interestingly it does seem to fail when I use `--vanilla` and only run the one test, but if I use `--vanilla` and run all 3 tests in the module it succeeds.

# Module tests + vanilla

```
>> $ ./manage.py test myproject.apps.help.tests.test_utils --no-migrations --vanilla
Creating test database for alias 'default'...
...
----------------------------------------------------------------------
Ran 3 tests in 0.050s

OK
Destroying test database for alias 'default'...
```

# Module tests + parallel

```
>> $ ./manage.py test myproject.apps.help.tests.test_utils --no-migrations --parallel
..E
======================================================================
ERROR: test_send_screen_share_alert (myproject.apps.help.tests.test_utils.HelpUtilsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/grant/Dev/django/myproject/myproject/apps/help/tests/test_utils.py", line 38, in test_send_screen_share_alert
    message = mail.outbox[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 3 tests in 8.021s

FAILED (errors=1)
```

# Single test + vanilla

```
>> $ ./manage.py test myproject.apps.help.tests.test_utils.HelpUtilsTests.test_send_screen_share_alert --no-migrations --vanilla
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_send_screen_share_alert (myproject.apps.help.tests.test_utils.HelpUtilsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/grant/Dev/django/myproject/myproject/apps/help/tests/test_utils.py", line 38, in test_send_screen_share_alert
    message = mail.outbox[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.026s

FAILED (errors=1)
```

# Single test + parallel

```
>> $ ./manage.py test myproject.apps.help.tests.test_utils.HelpUtilsTests.test_send_screen_share_alert --no-migrations --parallel
E
======================================================================
ERROR: test_send_screen_share_alert (myproject.apps.help.tests.test_utils.HelpUtilsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/grant/Dev/django/myproject/myproject/apps/help/tests/test_utils.py", line 38, in test_send_screen_share_alert
    message = mail.outbox[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 5.605s

FAILED (errors=1)
```

**Comment by ojii** [comment]
Awesome, thank you! (Sorry if I was a bit unclear before)

So the problem is definitely in your test. `--vanilla` means bypassing better-test completely, so if that test fails alone, it relies on one of the two other tests in `myproject.apps.help.tests.test_utils`.

Assuming the other two tests in your module are `test_one` and `test_two`, run:
- `./manage.py test myproject.apps.help.tests.test_utils.HelpUtilsTests.test_one myproject.apps.help.tests.test_utils.HelpUtilsTests.test_send_screen_share_alert --no-migrations --vanilla`
- `./manage.py test myproject.apps.help.tests.test_utils.HelpUtilsTests.test_two myproject.apps.help.tests.test_utils.HelpUtilsTests.test_send_screen_share_alert --no-migrations --vanilla`

This should show which of the other two tests is required for it to pass.

PS: It might no be 100% working right now, but you might wanna try the `--isolate` flag to run your whole test suite in isolation (one method at a time) to spot more issues like this. `--isolate` can be extremely slow.

**Comment by grantmcconnaughey** [comment]
You were right, @ojii. The failing test was dependent on the code from another test. I fixed that and the issue was fixed. Sorry about that. The error had never occurred until now.

**Comment by ojii** [comment]
Just pushed a change to master that hopefully makes `--isolate` more reliable. I recommend you do a pass with that flag as it might show other subtle bugs in your test suite (should they be present)

PS: I deprecated `--no-migrations`, by default it no doesn't run migrations but you can opt-in via `-migrate`.
