### ISSUE TITLE
Django 1.10 dropped optparse support

### ISSUE THREAD

**Issue by yakky** [ojii/django-better-test#7]
As a result https://github.com/ojii/django-better-test/blob/master/better_test/management/commands/test.py#L26 must be rewritten for argparse

**Comment by ojii** [comment]
Since I assume you already know the answer (if not, I'll investigate myself), what's the minimum Django version for argparse-based commands?

**Comment by yakky** [comment]
Django 1.8. From a cursory glance it should be possible to implement both interfaces in the same command, if you don't want to drop pre 1.8 support

**Comment by ojii** [comment]
Right now it supports all the way down to [1.6](https://github.com/ojii/django-better-test/blob/master/.travis.yml#L10) though maybe eventually I can drop some of the lower ones...
